#receivers:
#  otlp:
#    protocols:
#      grpc:
#        endpoint: localhost:4317
#      http:
#        endpoint: localhost:4318
#
#exporters:
#  zipkin:
#    endpoint: "http://zipkin:9411/api/v2/spans"
#  prometheus:
#    endpoint: "0.0.0.0:8889"
#
#processors:
#  batch:
#
#service:
#  pipelines:
#    traces:
#      receivers: [otlp]
#      processors: [batch]
#      exporters: [zipkin]
#    metrics:
#      receivers: [otlp]
#      processors: [batch]
#      exporters: [prometheus]
