server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/users-mgt
    username: users-mgt
    password: users-mgt
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

